### ISSUE TITLE
Make the display better.

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/YoutubeDataCollector#1]
The links should be categorized, and the look should be enhanced.

Currently, it is very cluttered and unreadable.

**Comment by vchrombie** [comment]
Can I contribute to this issue?

**Comment by vchrombie** [comment]
I want to make the list look little elegant.
I also want to add a shortcut to Youtube from the extension html itself.

**Comment by Parth-Vader** [comment]
@vchrombie If an issue exists, it means a PR is required. Don't ask it again and again. And also, come up with a PR that solves the issue (and other things that you may want to add) - and we discuss it at the PR what we want to remove.
