### ISSUE TITLE
Add a suitable favicon

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/YoutubeDataCollector#6]
Could be anything related to youtube + history.

**Comment by mritunjayz** [comment]
![128p](https://user-images.githubusercontent.com/22472097/33560775-b42b5f2c-d936-11e7-9776-a1f29151a954.png)
would it be better?

**Comment by Parth-Vader** [comment]
@mritunjaygoutam12 The watermark doesn't look great.

**Comment by vchrombie** [comment]
How about this icon?
![logo](https://github.com/vchrombie/Misc/blob/master/iconfinder-128.png?raw=true)

**Comment by Parth-Vader** [comment]
@vchrombie It should be related to history, youtube or something like that. This doesn't fit the description.

**Comment by vchrombie** [comment]
I remodelled the youtube logo with a specs instead of a play symbol symbolizing you are being watched.

**Comment by vchrombie** [comment]
How about this?

![logo](https://github.com/vchrombie/Misc/blob/master/imageedit_26_6927662987.png?raw=true)

I replaced the play symbol with the history symbol.

**Comment by Parth-Vader** [comment]
@vchrombie This looks perfect for the job. :+1:

**Comment by vchrombie** [comment]
Thanks!
Can I send a PR for this?

**Comment by Parth-Vader** [comment]
You never ask if you can send a PR if your idea is approved. You do it. ;)

**Comment by vchrombie** [comment]
Thank You!

**Comment by vchrombie** [comment]
How to integrate the logo?

`<link rel="icon" type="image/x-icon" href="#">`
in the history.html

Is it correct?
I am not able to do that.

**Comment by Parth-Vader** [comment]
@vchrombie Look at this [answer](https://stackoverflow.com/a/6940093/6517649). Also, ask your doubts in the slack channel instead.

**Comment by vchrombie** [comment]
I think this issue is solved now #9.
