### ISSUE TITLE
Beautify README

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/YoutubeDataCollector#7]
* GIFs could be added.
* It needs to more attractive - use of emojis, colors etc.
* Add badges (https://forthebadge.com/).

**Comment by vchrombie** [comment]
I am interested to work on this project.
Can I take this issue and work on this?

**Comment by Parth-Vader** [comment]
@vchrombie Sure.

**Comment by vchrombie** [comment]
Is it ok I use (http://shields.io/)?
Because you can create your own badges in shields.

I will create the style like that of (https://forthebadge.com/).

**Comment by Parth-Vader** [comment]
@vchrombie Sure, but should be related to the project.

**Comment by vchrombie** [comment]
Yeah, for sure. @Parth-Vader

**Comment by vchrombie** [comment]
I want to add..
"This extension works on Chrome, Firefox " in the README.md

No problem, right?

**Comment by Parth-Vader** [comment]
Hey, you can always send a PR - we can remove things we don't want there itself.
